import React, { useState } from "react";
import { SourcingProposal, UserRole } from "../types";
import {
  CheckCircle2,
  AlertTriangle,
  Sparkles,
  ArrowLeft,
  ThumbsUp,
  ThumbsDown,
  Zap,
  TrendingUp,
} from "lucide-react";

interface ApprovalViewProps {
  proposals: SourcingProposal[];
  onApproveProposal: (
    proposalId: string,
    selectedRank: number,
    customData?: { unitPrice: number; leadTimeDays: number; notes: string }
  ) => { success: boolean; message: string };
  onRejectProposal: (proposalId: string, reason: string) => void;
  userRole: UserRole;
  activeIncidentId?: string | null;
  onBack: () => void;
}

export const ApprovalView: React.FC<ApprovalViewProps> = ({
  proposals,
  onApproveProposal,
  onRejectProposal,
  userRole,
  onBack,
}) => {
  const [selectedProposalId, setSelectedProposalId] = useState<string | null>(
    proposals.find((p) => p.status === "Pending Approval")?.id || proposals[0]?.id || null
  );

  const [chosenRank, setChosenRank] = useState<number>(1);
  const [actionAlert, setActionAlert] = useState<{ type: "success" | "error"; text: string } | null>(null);

  const currentProposal = proposals.find((p) => p.id === selectedProposalId) || proposals[0];

  const handleApprove = (rank: number) => {
    if (!currentProposal) return;
    const result = onApproveProposal(currentProposal.id, rank);
    if (result.success) {
      setActionAlert({ type: "success", text: result.message });
    } else {
      setActionAlert({ type: "error", text: result.message });
    }
  };

  if (!currentProposal) {
    return (
      <div className="bg-white border border-slate-200 rounded-xl p-12 text-center space-y-4 shadow-sm">
        <CheckCircle2 className="w-10 h-10 text-emerald-600 mx-auto" />
        <h3 className="text-lg font-bold text-slate-900">No Proposals Pending Approval</h3>
        <p className="text-xs text-slate-500">All incidents have been resolved or no new backup proposals generated by PuLP MILP Solver.</p>
        <button
          onClick={onBack}
          className="px-4 py-2 bg-slate-900 hover:bg-slate-800 text-white rounded-lg font-semibold text-xs inline-flex items-center gap-2"
        >
          <ArrowLeft className="w-4 h-4" /> Back to Dashboard
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Light Minimalist Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-white border border-slate-200 p-6 rounded-xl shadow-sm">
        <div>
          <button onClick={onBack} className="text-xs font-semibold text-blue-600 hover:underline flex items-center gap-1 mb-2">
            <ArrowLeft className="w-3.5 h-3.5" /> Back to Operations
          </button>
          <h2 className="text-xl font-bold text-slate-900 flex items-center gap-2.5">
            <Sparkles className="w-6 h-6 text-amber-600" />
            1-Click Backup Sourcing Approval Board (PuLP MILP + GPT-4o)
          </h2>
          <p className="text-xs text-slate-500 mt-1">
            Multi-criteria optimization evaluating Top 1, 2, and 3 backup suppliers with 1-Click approval.
          </p>
        </div>
      </div>

      {actionAlert && (
        <div
          className={`p-4 rounded-xl text-xs font-semibold flex items-center gap-3 border ${
            actionAlert.type === "success"
              ? "bg-emerald-50 border-emerald-200 text-emerald-800"
              : "bg-red-50 border-red-200 text-red-800"
          }`}
        >
          {actionAlert.type === "success" ? <CheckCircle2 className="w-4 h-4 shrink-0 text-emerald-600" /> : <AlertTriangle className="w-4 h-4 shrink-0 text-red-600" />}
          <span>{actionAlert.text}</span>
        </div>
      )}

      {/* Main Content Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Sidebar: Proposals Selector */}
        <div className="space-y-3">
          <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wider">AI Sourcing Proposals</h3>
          <div className="space-y-2">
            {proposals.map((p) => {
              const isSelected = p.id === currentProposal.id;
              return (
                <button
                  key={p.id}
                  onClick={() => {
                    setSelectedProposalId(p.id);
                    setActionAlert(null);
                  }}
                  className={`w-full text-left p-3.5 rounded-xl border transition-all space-y-1.5 ${
                    isSelected
                      ? "bg-slate-900 border-slate-900 text-white shadow-sm"
                      : "bg-white border-slate-200 text-slate-900 hover:border-slate-300"
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <span className={`font-mono text-xs font-bold ${isSelected ? "text-cyan-300" : "text-blue-600"}`}>{p.poNumber}</span>
                    <span
                      className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
                        p.status === "Approved"
                          ? "bg-emerald-100 text-emerald-800 border border-emerald-200"
                          : "bg-amber-100 text-amber-800 border border-amber-200"
                      }`}
                    >
                      {p.status || "Pending Approval"}
                    </span>
                  </div>
                  <div className="text-xs font-semibold truncate">{p.skuName || p.sku}</div>
                  <div className={`text-[11px] flex items-center justify-between ${isSelected ? "text-slate-300" : "text-slate-500"}`}>
                    <span>Original: {p.originalSupplierName}</span>
                    <span className="font-mono font-bold">{p.rankings?.length || 0} Partners</span>
                  </div>
                </button>
              );
            })}
          </div>
        </div>

        {/* Right Panel: Proposals Top 1-3 Rankings */}
        <div className="lg:col-span-2 space-y-6">
          {/* Summary Box */}
          <div className="bg-white border border-slate-200 p-5 rounded-xl shadow-sm space-y-3.5">
            <div className="flex items-center justify-between border-b border-slate-100 pb-3">
              <div>
                <span className="text-xs font-mono font-bold text-blue-600">{currentProposal.id}</span>
                <h3 className="text-base font-bold text-slate-900 mt-0.5">
                  Order {currentProposal.poNumber} — SKU: {currentProposal.skuName || currentProposal.sku}
                </h3>
              </div>
              <span className="px-2.5 py-1 rounded-lg text-xs font-bold bg-amber-50 text-amber-800 border border-amber-200 flex items-center gap-1">
                <Zap className="w-3.5 h-3.5 text-amber-600" />
                PuLP MILP Solved
              </span>
            </div>

            {/* Baseline Details */}
            <div className="grid grid-cols-3 gap-3 bg-slate-50 p-3 rounded-lg border border-slate-200 text-xs">
              <div>
                <span className="text-slate-500 block">Original Supplier</span>
                <span className="font-semibold text-slate-900">{currentProposal.originalSupplierName}</span>
              </div>
              <div>
                <span className="text-slate-500 block">Original Unit Price</span>
                <span className="font-mono font-bold text-emerald-700">
                  {Number(currentProposal.originalUnitPrice).toLocaleString("en-US")} VND
                </span>
              </div>
              <div>
                <span className="text-slate-500 block">Ordered Quantity</span>
                <span className="font-mono font-bold text-slate-900">{currentProposal.quantity} units</span>
              </div>
            </div>

            {/* AI Recommendation Quote */}
            {currentProposal.recommendation && (
              <div className="p-3 bg-blue-50 border border-blue-200 rounded-lg text-xs text-slate-800 flex items-start gap-2.5">
                <Sparkles className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
                <div>
                  <span className="font-bold text-slate-900 block mb-0.5">AI Engine Recommendation (GPT-4o Reasoning):</span>
                  <p className="text-slate-700 leading-relaxed">{currentProposal.recommendation}</p>
                </div>
              </div>
            )}
          </div>

          {/* Top 1-3 Rankings Cards */}
          <div className="space-y-4">
            <h4 className="text-xs font-bold text-slate-700 flex items-center gap-2">
              <TrendingUp className="w-4 h-4 text-slate-900" />
              Optimized Backup Supplier Ranking (Top 1 - 3):
            </h4>

            {currentProposal.rankings?.map((item, idx) => (
              <div
                key={idx}
                className={`bg-white border rounded-xl p-5 shadow-sm space-y-3.5 ${
                  item.rank === 1 ? "border-amber-300 bg-amber-50/20" : "border-slate-200"
                }`}
              >
                <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                  <div className="flex items-center gap-3">
                    <span
                      className={`w-7 h-7 rounded-lg font-bold flex items-center justify-center text-xs font-mono ${
                        item.rank === 1 ? "bg-amber-500 text-white" : "bg-slate-200 text-slate-800"
                      }`}
                    >
                      #{item.rank}
                    </span>
                    <div>
                      <h4 className="text-sm font-bold text-slate-900">{item.supplierName}</h4>
                      <span className="text-[11px] text-slate-500 font-mono">Supplier ID: {item.supplierId}</span>
                    </div>
                  </div>

                  <div className="text-right">
                    <div className="text-[11px] text-slate-500">Optimization Score</div>
                    <div className="text-lg font-bold font-mono text-blue-600">{item.score}/100</div>
                  </div>
                </div>

                {/* Matrix */}
                <div className="grid grid-cols-3 gap-3 bg-slate-50 p-3 rounded-lg border border-slate-200 text-xs">
                  <div>
                    <span className="text-slate-500 block text-[11px]">Proposed Unit Price</span>
                    <span className="font-mono font-bold text-emerald-700">
                      {Number(item.unitPrice).toLocaleString("en-US")} VND
                    </span>
                  </div>
                  <div>
                    <span className="text-slate-500 block text-[11px]">Committed Lead Time</span>
                    <span className="font-mono font-bold text-slate-900">{item.leadTimeDays} days</span>
                  </div>
                  <div>
                    <span className="text-slate-500 block text-[11px]">Total Order Value</span>
                    <span className="font-mono font-bold text-amber-700">
                      {Number(item.totalCost || item.unitPrice * currentProposal.quantity).toLocaleString("en-US")} VND
                    </span>
                  </div>
                </div>

                {/* Pros & Cons */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
                  <div className="bg-emerald-50/60 border border-emerald-200 p-3 rounded-lg space-y-1">
                    <div className="font-bold text-emerald-800 flex items-center gap-1">
                      <ThumbsUp className="w-3.5 h-3.5 text-emerald-600" /> Key Advantages:
                    </div>
                    <ul className="space-y-0.5 text-slate-700">
                      {item.pros?.map((pro, pIdx) => (
                        <li key={pIdx} className="flex items-start gap-1">
                          <span className="text-emerald-600 font-bold">•</span>
                          <span>{pro}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div className="bg-red-50/60 border border-red-200 p-3 rounded-lg space-y-1">
                    <div className="font-bold text-red-800 flex items-center gap-1">
                      <ThumbsDown className="w-3.5 h-3.5 text-red-600" /> Risks & Drawbacks:
                    </div>
                    <ul className="space-y-0.5 text-slate-700">
                      {item.cons?.map((con, cIdx) => (
                        <li key={cIdx} className="flex items-start gap-1">
                          <span className="text-red-600 font-bold">•</span>
                          <span>{con}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>

                {/* 1-Click Action */}
                {(userRole === "supply_chain_manager" || userRole === "procurement_officer") && currentProposal.status !== "Approved" && (
                  <div className="pt-1 flex justify-end">
                    <button
                      onClick={() => handleApprove(item.rank)}
                      className={`px-4 py-2 rounded-lg text-xs font-bold flex items-center gap-1.5 transition-colors shadow-sm ${
                        item.rank === 1
                          ? "bg-amber-600 hover:bg-amber-700 text-white"
                          : "bg-slate-900 hover:bg-slate-800 text-white"
                      }`}
                    >
                      <CheckCircle2 className="w-4 h-4" />
                      Approve Option Top #{item.rank} (1-Click Approve)
                    </button>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
